services:
  mybackend:
    container_name: backendgym
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    links:
      - database
    volumes:
      - ./backend/uploads:/usr/src/app/uploads # Montar solo la carpeta uploads

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"

  myfrontend:
    container_name: frontgym
    restart: always
    build: ./frontclient
    ports:
      - "5173:5173"
    links:
      - mybackend
