services:
  mybackend:
    container_name: backendgym
    restart: always
    build: ./backend
    ports:
      - "5001:5000" # Cambiar puerto externo a 5001
    networks:
      - gym-network
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27018:27017" # Cambiar puerto externo a 27018
    networks:
      - gym-network

  myfrontend:
    container_name: frontgym
    restart: always
    build: ./frontclient
    ports:
      - "3000:5173" # Cambiar puerto externo a 3000
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge
