services:
  mybackend:
    container_name: backendgym
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    networks:
      - tailscale-network

  myfrontend:
    container_name: frontgym
    restart: always
    build: ./frontclient
    ports:
      - "5173:5173"
    depends_on:
      - mybackend
    volumes:
      - ./frontclient:/usr/src/app
    networks:
      - tailscale-network

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - tailscale-network
