services:
  mybackend:
    container_name: backendgym
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - gym-network
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads:/usr/src/app/uploads
    env_file:
      - ./backend/.env # Archivo .env específico del backend

  database:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - gym-network

  myfrontend:
    container_name: frontgym
    restart: always
    build: ./frontclient
    ports:
      - "5173:5173"
    networks:
      - gym-network
    env_file:
      - ./frontclient/.env # Archivo .env específico del frontend

networks:
  gym-network:
    driver: bridge
