import Ejercicio from "../models/ejercicio.model.js"; // Ajusta la ruta según sea necesario
import { connectDB } from "../db.js"; // Importa tu función de conexión

const ejerciciosPredeterminados = [
    //Principiante
    {
        "codigo": "00PRUBEA",
        "nombre": "PRUEBA",
        "descripcion": "PRUEBAAAAAAAAAAAAAAA",
        "nivel": "Principiante",
        "categoria": "Pecho",
        "series": 1,
        "duracion": 3,
        "descanso": 5,
        "repeticiones": 1,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pushup.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ001",
        "nombre": "Flexiones",
        "descripcion": "Ejercicio para fortalecer el pecho y tríceps.",
        "nivel": "Principiante",
        "categoria": "Pecho",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pushup.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ002",
        "nombre": "Sentadillas",
        "descripcion": "Ejercicio para fortalecer los muslos y glúteos.",
        "nivel": "Principiante",
        "categoria": "Piernas",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/sentadillas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ003",
        "nombre": "Planchas estaticas",
        "descripcion": "Ejercicio para fortalecer el core.",
        "nivel": "Principiante",
        "categoria": "Core",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/planchas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ004",
        "nombre": "Burpees",
        "descripcion": "Ejercicio para mejorar la resistencia cardiovascular.",
        "nivel": "Principiante",
        "categoria": "Cardio",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/burpees.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ005",
        "nombre": "Zancadas",
        "descripcion": "Ejercicio para fortalecer las piernas.",
        "nivel": "Principiante",
        "categoria": "Piernas",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/Zancadas.webp" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ006",
        "nombre": "Dominadas Elevados",
        "descripcion": "Ejercicio para fortalecer la espalda y los brazos.",
        "nivel": "Principiante",
        "categoria": "Espalda",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/dominadas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ007",
        "nombre": "Abdominales",
        "descripcion": "Ejercicio para fortalecer los músculos del abdomen.",
        "nivel": "Principiante",
        "categoria": "Abdomen",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/abdominales.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ008",
        "nombre": "Saltos en caja",
        "descripcion": "Ejercicio pliométrico para mejorar la explosividad.",
        "nivel": "Principiante",
        "categoria": "Pliometría",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/saltosencaja.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ009",
        "nombre": "Flexiones diamante",
        "descripcion": "Variación de flexiones para trabajar tríceps.",
        "nivel": "Principiante",
        "categoria": "Tríceps",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/flexionesdiamantes.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ010",
        "nombre": "Mountain climbers",
        "descripcion": "Ejercicio cardiovascular para quemar grasa.",
        "nivel": "Principiante",
        "categoria": "Cardio",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/mountainclimbers.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ011",
        "nombre": "Peso muerto",
        "descripcion": "Ejercicio compuesto para trabajar todo el cuerpo.",
        "nivel": "Principiante",
        "categoria": "Cuerpo Completo",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pesomuerto.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ012",
        "nombre": "Press de banca",
        "descripcion": "Ejercicio para fortalecer el pecho.",
        "nivel": "Principiante",
        "categoria": "Pecho",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressdebanca.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ013",
        "nombre": "Remo con barra en Punta",
        "descripcion": "Ejercicio para fortalecer la espalda.",
        "nivel": "Principiante",
        "categoria": "Espalda",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/remo-en-punta-gif.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ014",
        "nombre": "Press militar",
        "descripcion": "Ejercicio para fortalecer los hombros.",
        "nivel": "Principiante",
        "categoria": "Hombros",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressmilitar.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ015",
        "nombre": "Elevaciones laterales",
        "descripcion": "Ejercicio para los deltoides.",
        "nivel": "Principiante",
        "categoria": "Hombros",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/elevacioneslaterales.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ016",
        "nombre": "Correr",
        "descripcion": "Ejercicio para mejorar la resistencia cardiovascular.",
        "nivel": "Principiante",
        "categoria": "Cardio",
        "series": 1,
        "duracion": 180,
        "descanso": 60,
        "repeticiones": 2,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/correr.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ017",
        "nombre": "Bicicleta estacionaria",
        "descripcion": "Ejercicio cardiovascular para quemar calorías.",
        "nivel": "Principiante",
        "categoria": "Cardio",
        "series": 1,
        "duracion": 300,
        "descanso": 60,
        "repeticiones": 1,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/bicicletaestacionaria.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ018",
        "nombre": "Press francés",
        "descripcion": "Ejercicio para trabajar los tríceps.",
        "nivel": "Principiante",
        "categoria": "Tríceps",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressfrances.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ019",
        "nombre": "Curl de bíceps alternados",
        "descripcion": "Ejercicio para fortalecer los bíceps.",
        "nivel": "Principiante",
        "categoria": "Bíceps",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/curl-biceps-alterno-con-mancuernas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ020",
        "nombre": "Jumping Jacks",
        "descripcion": "Ejercicio para mejorar la resistencia y quemar calorías.",
        "nivel": "Principiante",
        "categoria": "Cardio",
        "series": 3,
        "duracion": 20,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/Jumpingjacks.gif" // Agregar URL de la imagen
    },
    //Intermedio
    {
        "codigo": "EJ021",
        "nombre": "Flexiones",
        "descripcion": "Ejercicio para fortalecer el pecho y tríceps.",
        "nivel": "Intermedio",
        "categoria": "Pecho",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pushup.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ022",
        "nombre": "Sentadillas",
        "descripcion": "Ejercicio para fortalecer los muslos y glúteos.",
        "nivel": "Intermedio",
        "categoria": "Piernas",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/sentadillas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ023",
        "nombre": "Planchas estaticas",
        "descripcion": "Ejercicio para fortalecer el core.",
        "nivel": "Intermedio",
        "categoria": "Core",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/planchas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ024",
        "nombre": "Burpees",
        "descripcion": "Ejercicio para mejorar la resistencia cardiovascular.",
        "nivel": "Intermedio",
        "categoria": "Cardio",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/burpees.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ025",
        "nombre": "Zancadas",
        "descripcion": "Ejercicio para fortalecer las piernas.",
        "nivel": "Intermedio",
        "categoria": "Piernas",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/Zancadas.webp" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ026",
        "nombre": "Dominadas Elevados",
        "descripcion": "Ejercicio para fortalecer la espalda y los brazos.",
        "nivel": "Intermedio",
        "categoria": "Espalda",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/dominadas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ027",
        "nombre": "Abdominales",
        "descripcion": "Ejercicio para fortalecer los músculos del abdomen.",
        "nivel": "Intermedio",
        "categoria": "Abdomen",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/abdominales.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ028",
        "nombre": "Saltos en caja",
        "descripcion": "Ejercicio pliométrico para mejorar la explosividad.",
        "nivel": "Intermedio",
        "categoria": "Pliometría",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/saltosencaja.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ029",
        "nombre": "Flexiones diamante",
        "descripcion": "Variación de flexiones para trabajar tríceps.",
        "nivel": "Intermedio",
        "categoria": "Tríceps",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/flexionesdiamantes.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ030",
        "nombre": "Mountain climbers",
        "descripcion": "Ejercicio cardiovascular para quemar grasa.",
        "nivel": "Intermedio",
        "categoria": "Cardio",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/mountainclimbers.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ031",
        "nombre": "Peso muerto",
        "descripcion": "Ejercicio compuesto para trabajar todo el cuerpo.",
        "nivel": "Intermedio",
        "categoria": "Cuerpo Completo",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pesomuerto.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ032",
        "nombre": "Press de banca",
        "descripcion": "Ejercicio para fortalecer el pecho.",
        "nivel": "Intermedio",
        "categoria": "Pecho",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressdebanca.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ033",
        "nombre": "Remo con barra en Punta",
        "descripcion": "Ejercicio para fortalecer la espalda.",
        "nivel": "Intermedio",
        "categoria": "Espalda",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/remo-en-punta-gif.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ034",
        "nombre": "Press militar",
        "descripcion": "Ejercicio para fortalecer los hombros.",
        "nivel": "Intermedio",
        "categoria": "Hombros",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressmilitar.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ035",
        "nombre": "Elevaciones laterales",
        "descripcion": "Ejercicio para los deltoides.",
        "nivel": "Intermedio",
        "categoria": "Hombros",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/elevacioneslaterales.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ036",
        "nombre": "Correr",
        "descripcion": "Ejercicio para mejorar la resistencia cardiovascular.",
        "nivel": "Intermedio",
        "categoria": "Cardio",
        "series": 1,
        "duracion": 300,
        "descanso": 60,
        "repeticiones": 1,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/correr.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ037",
        "nombre": "Bicicleta estacionaria",
        "descripcion": "Ejercicio cardiovascular para quemar calorías.",
        "nivel": "Intermedio",
        "categoria": "Cardio",
        "series": 1,
        "duracion": 600,
        "descanso": 60,
        "repeticiones": 1,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/bicicletaestacionaria.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ038",
        "nombre": "Press francés",
        "descripcion": "Ejercicio para trabajar los tríceps.",
        "nivel": "Intermedio",
        "categoria": "Tríceps",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressfrances.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ039",
        "nombre": "Curl de bíceps alternados",
        "descripcion": "Ejercicio para fortalecer los bíceps.",
        "nivel": "Intermedio",
        "categoria": "Bíceps",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/curl-biceps-alterno-con-mancuernas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ040",
        "nombre": "Jumping Jacks",
        "descripcion": "Ejercicio para mejorar la resistencia y quemar calorías.",
        "nivel": "Intermedio",
        "categoria": "Cardio",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 10,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/Jumpingjacks.gif" // Agregar URL de la imagen
    },
    //Avanzado
    {
        "codigo": "EJ041",
        "nombre": "Flexiones",
        "descripcion": "Ejercicio para fortalecer el pecho y tríceps.",
        "nivel": "Avanzado",
        "categoria": "Pecho",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pushup.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ042",
        "nombre": "Sentadillas",
        "descripcion": "Ejercicio para fortalecer los muslos y glúteos.",
        "nivel": "Avanzado",
        "categoria": "Piernas",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/sentadillas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ043",
        "nombre": "Planchas estaticas",
        "descripcion": "Ejercicio para fortalecer el core.",
        "nivel": "Avanzado",
        "categoria": "Core",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/planchas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ044",
        "nombre": "Burpees",
        "descripcion": "Ejercicio para mejorar la resistencia cardiovascular.",
        "nivel": "Avanzado",
        "categoria": "Cardio",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/burpees.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ045",
        "nombre": "Zancadas",
        "descripcion": "Ejercicio para fortalecer las piernas.",
        "nivel": "Avanzado",
        "categoria": "Piernas",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/Zancadas.webp" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ046",
        "nombre": "Dominadas Elevados",
        "descripcion": "Ejercicio para fortalecer la espalda y los brazos.",
        "nivel": "Avanzado",
        "categoria": "Espalda",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/dominadas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ047",
        "nombre": "Abdominales",
        "descripcion": "Ejercicio para fortalecer los músculos del abdomen.",
        "nivel": "Avanzado",
        "categoria": "Abdomen",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/abdominales.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ048",
        "nombre": "Saltos en caja",
        "descripcion": "Ejercicio pliométrico para mejorar la explosividad.",
        "nivel": "Avanzado",
        "categoria": "Pliometría",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/saltosencaja.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ049",
        "nombre": "Flexiones diamante",
        "descripcion": "Variación de flexiones para trabajar tríceps.",
        "nivel": "Avanzado",
        "categoria": "Tríceps",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/flexionesdiamantes.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ050",
        "nombre": "Mountain climbers",
        "descripcion": "Ejercicio cardiovascular para quemar grasa.",
        "nivel": "Avanzado",
        "categoria": "Cardio",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/mountainclimbers.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ051",
        "nombre": "Peso muerto",
        "descripcion": "Ejercicio compuesto para trabajar todo el cuerpo.",
        "nivel": "Avanzado",
        "categoria": "Cuerpo Completo",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pesomuerto.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ052",
        "nombre": "Press de banca",
        "descripcion": "Ejercicio para fortalecer el pecho.",
        "nivel": "Avanzado",
        "categoria": "Pecho",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressdebanca.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ053",
        "nombre": "Remo con barra en Punta",
        "descripcion": "Ejercicio para fortalecer la espalda.",
        "nivel": "Avanzado",
        "categoria": "Espalda",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/remo-en-punta-gif.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ054",
        "nombre": "Press militar",
        "descripcion": "Ejercicio para fortalecer los hombros.",
        "nivel": "Avanzado",
        "categoria": "Hombros",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressmilitar.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ055",
        "nombre": "Elevaciones laterales",
        "descripcion": "Ejercicio para los deltoides.",
        "nivel": "Avanzado",
        "categoria": "Hombros",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/elevacioneslaterales.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ056",
        "nombre": "Correr",
        "descripcion": "Ejercicio para mejorar la resistencia cardiovascular.",
        "nivel": "Avanzado",
        "categoria": "Cardio",
        "series": 1,
        "duracion": 540,
        "descanso": 60,
        "repeticiones": 1,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/correr.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ057",
        "nombre": "Bicicleta estacionaria",
        "descripcion": "Ejercicio cardiovascular para quemar calorías.",
        "nivel": "Avanzado",
        "categoria": "Cardio",
        "series": 1,
        "duracion": 900,
        "descanso": 60,
        "repeticiones": 1,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/bicicletaestacionaria.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ058",
        "nombre": "Press francés",
        "descripcion": "Ejercicio para trabajar los tríceps.",
        "nivel": "Avanzado",
        "categoria": "Tríceps",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/pressfrances.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ059",
        "nombre": "Curl de bíceps alternados",
        "descripcion": "Ejercicio para fortalecer los bíceps.",
        "nivel": "Avanzado",
        "categoria": "Bíceps",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/curl-biceps-alterno-con-mancuernas.gif" // Agregar URL de la imagen
    },
    {
        "codigo": "EJ060",
        "nombre": "Jumping Jacks",
        "descripcion": "Ejercicio para mejorar la resistencia y quemar calorías.",
        "nivel": "Avanzado",
        "categoria": "Cardio",
        "series": 4,
        "duracion": 30,
        "descanso": 10,
        "repeticiones": 15,
        "estado": "En proceso",
        "imagen": "http://localhost:5000/uploads/ejercicios/Jumpingjacks.gif" // Agregar URL de la imagen
    }
];

const seedEjercicios = async () => {
    try {
        await connectDB();

        // Verificar si ya existen documentos en la colección
        const count = await Ejercicio.countDocuments();
        if (count > 0) {
            console.log("Los ejercicios ya existen en la base de datos. Seeding no es necesario.");
            return;
        }

        // Inserta los ejercicios predeterminados
        const result = await Ejercicio.insertMany(ejerciciosPredeterminados);
        console.log("Datos predeterminados agregados:", result);
    } catch (error) {
        console.error("Error al agregar datos:", error);
    }
};

export default seedEjercicios;